version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: demo_run
    image: demo-webapp
    init: true
    environment:
      - CMD=src/app.py
      - ARG=demo
    env_file:
      - app.env
  db:
    image: public.ecr.aws/docker/library/postgres:16.0-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "--user=postgres", "--port=5432", "--timeout=3"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: postgres


  